### DISCUSSION TITLE
Heat meter support?

### DISCUSSION THREAD

**Discussion by WolfgangFahl** [UtilitechAS/amsreader-firmware#908] [Q&A]
I would like get a heatmeter read over Wifi and have a hard time getting that work with a standard Optical over the AIR device. I can successfully read my heatmeter with https://github.com/WolfgangFahl/mbusreader e.g. i get the json response below in pyMeterBus format. The problem seems to be the wakeup sequence. Is your hardware / software prepared for heat meters e.g as described in https://github.com/WolfgangFahl/mbusreader/blob/main/mbusread_examples/mbus_config.yaml? 

```
{
  "body": {
    "header": {
      "access_no": 47,
      "identification": "0x24, 0x01, 0x66, 0x00",
      "manufacturer": "ACW",
      "medium": "0x4",
      "sign": "0x0, 0x0",
      "status": "0x10",
      "type": "0x72",
      "version": "0x9"
    },
    "records": [
      {
        "function": "FunctionType.INSTANTANEOUS_VALUE",
        "storage_number": 0,
        "type": "VIFUnit.FABRICATION_NO",
        "unit": "MeasureUnit.NONE",
        "value": 24016600
      },
      {
        "function": "FunctionType.INSTANTANEOUS_VALUE",
        "storage_number": 0,
        "type": "VIFUnit.ENERGY_WH",
        "unit": "MeasureUnit.WH",
        "value": 0
      },
      {
        "function": "FunctionType.INSTANTANEOUS_VALUE",
        "storage_number": 0,
        "type": "VIFUnit.VOLUME",
        "unit": "MeasureUnit.M3",
        "value": 0
      },
      {
        "function": "FunctionType.ERROR_STATE_VALUE",
        "storage_number": 0,
        "type": "VIFUnit.POWER_W",
        "unit": "MeasureUnit.W",
        "value": 99999900
      },
      {
        "function": "FunctionType.ERROR_STATE_VALUE",
        "storage_number": 0,
        "type": "VIFUnit.VOLUME_FLOW",
        "unit": "MeasureUnit.M3_H",
        "value": 999.999
      },
      {
        "function": "FunctionType.INSTANTANEOUS_VALUE",
        "storage_number": 0,
        "type": "VIFUnit.FLOW_TEMPERATURE",
        "unit": "MeasureUnit.C",
        "value": 20.5
      },
      {
        "function": "FunctionType.INSTANTANEOUS_VALUE",
        "storage_number": 0,
        "type": "VIFUnit.RETURN_TEMPERATURE",
        "unit": "MeasureUnit.C",
        "value": 20.200000000000003
      },
      {
        "function": "FunctionType.INSTANTANEOUS_VALUE",
        "storage_number": 0,
        "type": "VIFUnit.TEMPERATURE_DIFFERENCE",
        "unit": "MeasureUnit.K",
        "value": 0.22
      },
      {
        "function": "FunctionType.INSTANTANEOUS_VALUE",
        "storage_number": 0,
        "type": "VIFUnit.DATE_TIME_GENERAL",
        "unit": "MeasureUnit.DATE_TIME",
        "value": "2025-01-26T16:34"
      },
      {
        "function": "FunctionType.INSTANTANEOUS_VALUE",
        "storage_number": 0,
        "type": "VIFUnit.OPERATING_TIME",
        "unit": "MeasureUnit.SECONDS",
        "value": 20736000
      },
      {
        "function": "FunctionType.INSTANTANEOUS_VALUE",
        "storage_number": 0,
        "type": "VIFUnitExt.FIRMWARE_VERSION",
        "unit": "MeasureUnit.NONE",
        "value": 22
      },
      {
        "function": "FunctionType.INSTANTANEOUS_VALUE",
        "storage_number": 0,
        "type": "VIFUnitExt.SOFTWARE_VERSION",
        "unit": "MeasureUnit.NONE",
        "value": 47
      },
      {
        "function": "FunctionType.SPECIAL_FUNCTION",
        "storage_number": 0,
        "type": "None",
        "unit": "None",
        "value": "20 00"
      }
    ]
  },
  "head": {
    "a": "0x0",
    "c": "0x8",
    "crc": "0xc6",
    "length": "0x4d",
    "start": "0x68",
    "stop": "0x16"
  }
}
```

**Comment by ArnieO** [comment]
I am not familiar with the term "heat meter". 

The firmware is prepared for reading two types of temperature sensors:
- Analogue temperature sensor (analogue read)
- One specific type of digital temperature sensor: Dallas DS18B20

Such sensors are not included on our devices, but can be installed by the user - see the device technical descriptions:
- https://wiki.amsleser.no/en/Pow-U
- https://wiki.amsleser.no/en/pow-k
- https://wiki.amsleser.no/en/pow-p1

**Comment by WolfgangFahl** [comment]
@ArnieO The yaml file had two doc urls for two devices : Itron CF Echo 2 and Ultramaxx
![grafik](https://github.com/user-attachments/assets/4b6f98de-1038-4907-8e12-43b030a89da1)

These devices come with an IR Optical connector (or optional direct M-Bus) connector.  

If you would support these and sell in germany it would be a good start. A similar devices to be supported can be found at https://docs.bitshake.de/script/
```
Engelmann SensoStar E 

 

>D

wkup=1

>B

>S

if ((upsecs==1) or (upsecs%2700==0)) {

print wakeup start

;set serial protocol

sml(-1 1 "2400:8N1")

;send 0x55 for 2,2 seconds with 8N1 (53x), 2400 baud (wakeup sequence)

for wkup 1 53 1

sml(1 1 "55555555555555555555")

next

print wakeup end

wkup=1

print wait for the meter

delay(350)

;switch serial protocol

sml(-1 1 "2400:8E1")

print init MBus (1040004016); scan for device 00

sml(1 1 "1040004016")

delay(350)

print request current data (107BFE7916)

sml(1 1 "107BFE7916")

}

>M 1

+1,5,rE1,0,2400,WAERME,4

1,=so3,32

1,0478u32s@1,Zählernummer,,Zählernummer,0

1,0406u32s@1000,Energie,MWh,Energie,3

1,0413u32s@1000,Volumen,m³,Volumen,3

1,042bu32s@1,Leistung,W,Leistung,0

1,142bu32s@1,Max. Leistung,W,Max. Leistung,0

1,043bu32s@1000,Volumenstrom,m³/h,Volumenstrom,3

1,143bu32s@1000,Max. Volumenstrom,m³/h,Max. Volumenstrom,3

1,025buuUU@1,Vorlauftemperatur,°C,Vorlauftemperatur,0

1,025fuuUU@1,Rücklauftemperatur,°C,Rücklauftemperatur,0

1,0261ssSS@100,Temperaturdifferenz,°C,Temperaturdifferenz,2

1,0223uuUU@1,Betriebsdauer,Tage,Betriebsdauer,0

1,4406u32s@1000,Stichtag Energie,MWh,Letzter Stichtag Energie,3

1,4413u32s@1000,Stichtag Volumen,m³,Letzter Stichtag Volumen,3

#
```

so basically we are talking about the digital communication via serial with wakeup and specific MBUS commands.I was under the impression that your devices are in principle ready to do this. Unfortunately your webshop is not open for german customers.

**Reply by ArnieO** [reply]
We do not officially support reading from such devices, even if (which I do not know whether is the case) the content of the payloads use OBIS codes - and could theoretically be "unwrapped". You are welcome to try - but you will probably need to make adjustments to the code. And we do not have capacity to provide support for such amendments - thank you for your understanding. 

> Unfortunately your webshop is not open for german customers.

German customers are invited to place orders on https://lectronz.com/stores/amsleser - but they should know that our devices and firmware will not work on German smart power meters. Known supported meters can be found in our [Selection guide](https://www.amsleser.no/index.php?fc=module&module=ams_selector&controller=display).

**Comment by avandorp** [comment]
Many heat meters can be read by https://github.com/wmbusmeters/wmbusmeters/. But it's not something you usually run on an ESP, so probably doesn't fit your requirements exactly. The AMSReader is heavily geared towards electricity meters, even though hardware and parts of the software would be reusable for your use case. (Writing this as a _user_ of both AMSReader and wmbusmeters.

**Comment by WolfgangFahl** [comment]
@avandorp  unfortunately i was not aware of the capabilities of libmus and wmbusmeters when i started the https://github.com/WolfgangFahl/mbusreader project with a demo at https://mbus.bitplan.com/. The main obstacle was the wakeup sequence which i still do not get working e.g. from https://docs.bitshake.de/script/ - i find that quite frustrating and wonder why it would be so hard to get the m-bus MQTT translation for such devices on an esp chip and package it as https://bitshake.de in principle did. I find it important to introduce a proper layer/separation of concern architecture in these matters. MQTT is so much easier to handle. If i would have to spent EUR 50-100 for a solution that would cost me a lot less than the effort i had so far. Currently i need a raspi 3 as an intermediate which is just awkward and eating up more power than necessary. The raspi can run all three solutions: libmus, wmbusmeter or my own proposal. It's IMHO just a question of configuration. My proposal is to use YAML such as shown in https://github.com/WolfgangFahl/mbusreader/tree/main/mbusread_examples and used in the example the main config being https://github.com/WolfgangFahl/mbusreader/blob/main/mbusread_examples/mbus_config.yaml

with a proper structure manufacturers/devices/messages
```yaml
manufacturers:
  allmess:
    name: Allmess/Itron
    url: https://www.allmess.de
    country: Germany

    devices:
      cf_echo_ii:
        model: CF Echo II
        title: ''
        doc_url: https://www.allmess.de/fileadmin/multimedia/alle_Dateien/MA/MA_BA_12088-AC%20CF%20Echo%20II%20D%20TS1021_KL.pdf
        has_echo: True
        wakeup_pattern: "55"
        wakeup_times: 528
        wakeup_delay: 0.350
        messages:
          read1:
            name: Basic Reading
            title: Standard M-Bus reading
            hex: 684d4d680800722654832277040904360000000c78265483220406493500000c14490508000b2d0000000b3b0000000a5a18060a5e89020b61883200046d0d0c2c310227c80309fd0e2209fd0f470f00008d16
          init:
            name: init write
            title: CF Echo II init
            hex: 6803036873fea61716
          read_data:
            name: read data cmd
            title: CF Echo II read data command
            hex: 105BFE5916
 ```
