### ISSUE TITLE
Skipping hour reading

### ISSUE THREAD

**Issue by SVH-Powel** [UtilitechAS/amsreader-firmware#743]
**Describe the bug**
Tonight at 02:00 an hour reading was skipped. That is not a huge problem, but I find it irritating that the monthly max values are destroyed for the rest of the month.

I found no messages sent on mqtt either. And as you can see from the screenshot, there was no booting. The powu+ is on usb power and signal strength is -64dbm. Cable length to HAN interface is 1m.

**Screenshots**
![Screenshot_20240305-061341](https://github.com/UtilitechAS/amsreader-firmware/assets/64255194/87c917b7-88a7-46e0-b351-41c6aba95887)
![Screenshot_20240305-061311](https://github.com/UtilitechAS/amsreader-firmware/assets/64255194/e5eee379-fb01-49e7-97f7-8770521ec9bf)

**Hardware information:**
 - Country: Norway
 - Meter: Aidon
 - Encryption enabled no
 - AMS reader: Pow-U+

**Relevant firmware information:**
 - Version: 2.2.28
 - MQTT: yes
 - MQTT payload type: Raw
 - HAN baud and parity: 2400 8E1
 - ENTSO-E API enabled: no

**Comment by SVH-Powel** [comment]
Additional info, but perhaps completely irrelevant:

It was running for 3 weeks in february with maximum power saving and on only HAN power. But it was booting often, probably because of low power available, but I don't know.

1 of march I got it connected to USB power and I also turned power saving off. 5 days later, this happens, but of course, a coincidence.

**Comment by ArnieO** [comment]
Interesting, as we had a similar bug report very recently. 
When a whole-hour reading is skipped, the reader should average when it receives the next whole-hour reading with accumulated energy [kWh]. That did not happen here, it seems to have logged "zero" first, then the consumption for two hours.

Can you post what you get when you add "monthplot.json" to the URL?
That will show the numbers behind that graph. I want to see if the value is 0.00 for that period, or if there is some small number (for some reason). 

Then we need to figure out why the averaging in some cases fails. -> @gskjold

**Comment by stigvi** [comment]
> Interesting, as we had a similar bug report very recently. When a whole-hour reading is skipped, the reader should average when it receives the next whole-hour reading with accumulated energy [kWh]. That did not happen here, it seems to have logged "zero" first, then the consumption for two hours.
> 
> Can you post what you get when you add "monthplot.json" to the URL? That will show the numbers behind that graph. I want to see if the value is 0.00 for that period, or if there is some small number (for some reason).
> 
> Then we need to figure out why the averaging in some cases fails. -> @gskjold

There does not seem to be any problem with the daily data for the whole month. It is only one hour missing.

**Comment by ArnieO** [comment]
> There does not seem to be any problem with the daily data for the whole month. It is only one hour missing.

Sorry, my bad. 
Please add "/dayplot.json" to the URL and post the output.

**Comment by stigvi** [comment]
{
    "i00": 8.17,
    "i01": 4.78,
    "i02": 4.81,
    "i03": 4.75,
    "i04": 4.36,
    "i05": 2.86,
    "i06": 2.54,
    "i07": 2.93,
    "i08": 3.08,
    "i09": 3.01,
    "i10": 2.72,
    "i11": 2.39,
    "i12": 4.75,
    "i13": 4.3,
    "i14": 3.25,
    "i15": 3.84,
    "i16": 3.42,
    "i17": 2.64,
    "i18": 2.07,
    "i19": 2.16,
    "i20": 2.76,
    "i21": 4.21,
    "i22": 3.84,
    "i23": 0,
    "e00": 0,
    "e01": 0,
    "e02": 0,
    "e03": 0,
    "e04": 0,
    "e05": 0,
    "e06": 0,
    "e07": 0,
    "e08": 0,
    "e09": 0,
    "e10": 0,
    "e11": 0,
    "e12": 0,
    "e13": 0,
    "e14": 0,
    "e15": 0,
    "e16": 0,
    "e17": 0,
    "e18": 0,
    "e19": 0,
    "e20": 0,
    "e21": 0,
    "e22": 0,
    "e23": 0
}

![image](https://github.com/UtilitechAS/amsreader-firmware/assets/25978315/128e2430-caa0-4392-8ed3-b0d73e5561cf)

**Comment by ArnieO** [comment]
Thank you - this confirms the registered value is 0.00. 
Then @gskjold needs to figure out what happens here, as normal behavior is averaging (periods 00 and 01 should be identical, at 4.09).

**Comment by ArnieO** [comment]
See update on https://github.com/UtilitechAS/amsreader-firmware/issues/717.
Potentially linked.

**Comment by stigvi** [comment]
Happened again last evening. I am not sure how useful these reports are. You have to make some sort of better debugging to catch errors like this which happens each 14+++ days. Since the last time this happened in the beginning of march, I increased the buffer from 256 to 512. But that didn't help.

Device is a Pow-U+ on usb power and good wifi. Cable length to meter is 0.5m and the meter is an Aidon 6534.

![Screenshot_20240321_215528_Edge](https://github.com/UtilitechAS/amsreader-firmware/assets/25978315/3bb63f5b-85b8-4429-9b78-8621bab023a0)

**Comment by ArnieO** [comment]
> You have to make some sort of better debugging to catch errors like this which happens each 14+++ days.

Yes, the fact that it appears very seldom amongst very few users makes it difficult to debug.
Your idea is to implement some kind of debug sensor that would forward some kind of debug data to HA. 
Let us hear what @gskjold thinks about that proposition.

**Comment by stigvi** [comment]
3rd time this month. And this time it really messes up the tariff peaks.

I set the power saving to off a few days ago and I have a feeling that this happens more often when this setting is off.

![image](https://github.com/UtilitechAS/amsreader-firmware/assets/25978315/1f887ce3-c1d6-4505-a24c-a23f3803ad31)

**Comment by stigvi** [comment]
Question:

If I use "Default" as setting on Power Saving, does that mean that wifi.setsleep is not called / used in this code section?

if(WiFi.begin(wifi.ssid, wifi.psk)) {
			if(wifi.sleep <= 2) {
				switch(wifi.sleep) {
					case 0:
						WiFi.setSleep(WIFI_PS_NONE);
						break;
					case 1:
						WiFi.setSleep(WIFI_PS_MIN_MODEM);
						break;
					case 2:
						WiFi.setSleep(WIFI_PS_MAX_MODEM);
						break;
				}
			}

**Comment by stigvi** [comment]
According to the documentation for the espressif library, WiFi.setSleep() only accept a boolean as a parameter, but that is not how it is used in your code. But there is a lot of code here, so I might have overlooked something.....

**Comment by gskjold** [comment]
There are two ways of setting sleep, one with boolean and one with wifi_ps_type_t:
https://github.com/espressif/arduino-esp32/blob/abc01331a272663cbd596e7d2a28dd31b491d265/libraries/WiFi/src/WiFiGeneric.cpp#L1377

Default will not call setsleep in our code, which will default to whatever is standard in arduino. Currently that is minimum, as you already pointed out.

**Comment by gskjold** [comment]
I don't know how often this issue is presenting itself, but I have made some adjustments in the latest development build that may fix it, see #738

**Comment by gskjold** [comment]
For anyone who have upgraded to 2.3, have you experience this since?

**Comment by stigvi** [comment]
> For anyone who have upgraded to 2.3, have you experience this since?

It happened 2-3 times each month so too soon to tell. After the summer, I can give you an answer if it doesn't happen before that.

**Comment by stigvi** [comment]
No, it has not changed to anything better. I wish you could have some sort of resetting the month max values manually because they are useless now until they are reset automatically on 1st of may.

![image](https://github.com/UtilitechAS/amsreader-firmware/assets/25978315/b948f0fb-717a-4e8f-86b2-a14a9e79ca74)

![image](https://github.com/UtilitechAS/amsreader-firmware/assets/25978315/3cb9213d-d120-46c7-8c68-99323ad95418)

**Comment by stigvi** [comment]
It look like I am in fact receiving data on the mqtt interface for the missing hour. The reported value is identical to the last hours value.

```
from_state:
    entity_id: sensor.klepp_energi_total_energi
    state: '109241.592'
    attributes:
      state_class: total_increasing
      unit_of_measurement: kWh
      device_class: energy
      friendly_name: Klepp Energi Total Energi
    last_changed: '2024-04-13T04:00:12.261360+00:00'
    last_reported: '2024-04-13T04:00:12.261360+00:00'
    last_updated: '2024-04-13T04:00:12.261360+00:00'
    context:
      id: 01HVASSRF5DM1GVZFR7E4EWVPH
      parent_id: null
      user_id: null
to_state:
    entity_id: sensor.klepp_energi_total_energi
    state: '109241.592'
    attributes:
      state_class: total_increasing
      unit_of_measurement: kWh
      device_class: energy
      friendly_name: Klepp Energi Total Energi
    last_changed: '2024-04-13T05:00:12.396898+00:00'
    last_reported: '2024-04-13T05:00:12.396898+00:00'
    last_updated: '2024-04-13T05:00:12.396898+00:00'
    context:
      id: 01HVAX7M7CBFMR4948DGDZ97JK
      parent_id: null
      user_id: null
```
